name = "opentui"
version = "0.1.0"
gleam = ">= 1.15.0"

target = "javascript"

[javascript]
runtime = "bun"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_javascript = ">= 0.13.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
